# Generated by Django 5.0.4 on 2024-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sales', models.CharField(max_length=100)),
                ('attendance', models.PositiveIntegerField(verbose_name=300)),
                ('linen', models.TextField()),
                ('stage', models.TextField()),
                ('notes', models.TextField()),
                ('alcohol', models.TextField()),
            ],
        ),
    ]
